# Generated by Django 4.1.7 on 2023-03-05 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syfty', '0002_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Syft',
        ),
    ]
