# Generated by Django 4.1.7 on 2023-03-12 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syfts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syft',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='syft',
            name='notifications_sent',
            field=models.IntegerField(default=0),
        ),
    ]
